
#服务器的数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  云服务器上的nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.219.47.26:8848